/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSnowRemovalRouteImport } from './routes/services.snow-removal'
import { Route as ServicesRetainingWallsRouteImport } from './routes/services.retaining-walls'
import { Route as ServicesIrrigationRepairRouteImport } from './routes/services.irrigation-repair'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSnowRemovalRoute = ServicesSnowRemovalRouteImport.update({
  id: '/services/snow-removal',
  path: '/services/snow-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRetainingWallsRoute = ServicesRetainingWallsRouteImport.update({
  id: '/services/retaining-walls',
  path: '/services/retaining-walls',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIrrigationRepairRoute =
  ServicesIrrigationRepairRouteImport.update({
    id: '/services/irrigation-repair',
    path: '/services/irrigation-repair',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/irrigation-repair': typeof ServicesIrrigationRepairRoute
  '/services/retaining-walls': typeof ServicesRetainingWallsRoute
  '/services/snow-removal': typeof ServicesSnowRemovalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/irrigation-repair': typeof ServicesIrrigationRepairRoute
  '/services/retaining-walls': typeof ServicesRetainingWallsRoute
  '/services/snow-removal': typeof ServicesSnowRemovalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/irrigation-repair': typeof ServicesIrrigationRepairRoute
  '/services/retaining-walls': typeof ServicesRetainingWallsRoute
  '/services/snow-removal': typeof ServicesSnowRemovalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/services/irrigation-repair'
    | '/services/retaining-walls'
    | '/services/snow-removal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/services/irrigation-repair'
    | '/services/retaining-walls'
    | '/services/snow-removal'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/services/irrigation-repair'
    | '/services/retaining-walls'
    | '/services/snow-removal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesIrrigationRepairRoute: typeof ServicesIrrigationRepairRoute
  ServicesRetainingWallsRoute: typeof ServicesRetainingWallsRoute
  ServicesSnowRemovalRoute: typeof ServicesSnowRemovalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/snow-removal': {
      id: '/services/snow-removal'
      path: '/services/snow-removal'
      fullPath: '/services/snow-removal'
      preLoaderRoute: typeof ServicesSnowRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/retaining-walls': {
      id: '/services/retaining-walls'
      path: '/services/retaining-walls'
      fullPath: '/services/retaining-walls'
      preLoaderRoute: typeof ServicesRetainingWallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/irrigation-repair': {
      id: '/services/irrigation-repair'
      path: '/services/irrigation-repair'
      fullPath: '/services/irrigation-repair'
      preLoaderRoute: typeof ServicesIrrigationRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesIrrigationRepairRoute: ServicesIrrigationRepairRoute,
  ServicesRetainingWallsRoute: ServicesRetainingWallsRoute,
  ServicesSnowRemovalRoute: ServicesSnowRemovalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
